name: example-api
description: Test API Box with route restrictions
authors:
  - name: Test User
    email: test@email.com
remotes:
  - remote_with_restrictions
  - remote_with_allowed_routes
  - remote_with_custom_mapping

# Non-remote endpoints (API Box's own endpoints)
endpoints:
  - "/"                    # API metadata and information

# Global restrictions (applied to all remotes unless overridden)
restricted:
  - users/{{}}/delete